"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authorization_1 = require("../../middlewares/authorization");
const getAllCourses_1 = require("../../controllers/courses/getAllCourses");
const getExternalCourseDetails_1 = require("../../controllers/courses/getExternalCourseDetails");
const registerACourse_1 = require("../../controllers/courses/registerACourse");
const getStudentCourses_1 = require("../../controllers/courses/getStudentCourses");
const getStudentCourseDetails_1 = require("../../controllers/courses/getStudentCourseDetails");
const markCourseCompleted_1 = require("../../controllers/courses/markCourseCompleted");
const getCompletedCourses_1 = require("../../controllers/courses/getCompletedCourses");
const getUncompletedCourses_1 = require("../../controllers/courses/getUncompletedCourses");
const router = (0, express_1.Router)();
router.get('/all_courses', authorization_1.authoriser, getAllCourses_1.getAllCourses);
router.get('/single_course/:course_code', authorization_1.authoriser, getExternalCourseDetails_1.getExternalCourseDetails);
router.post('/register_course/:course_code', authorization_1.authoriser, registerACourse_1.registerACourse);
router.get('/student_courses', authorization_1.authoriser, getStudentCourses_1.getStudentEnrolledCourses);
router.get('/single_student_course/:course_code', authorization_1.authoriser, getStudentCourseDetails_1.getStudentCourseDetails);
router.patch('/mark_completed/:course_code', authorization_1.authoriser, markCourseCompleted_1.markAsCompleted);
router.get('/completed_courses', authorization_1.authoriser, getCompletedCourses_1.getStudentCompletedCourses);
router.get('/uncompleted_courses', authorization_1.authoriser, getUncompletedCourses_1.getStudentUncompletedCourses);
exports.default = router;
